kind: Service
apiVersion: v1
metadata:
  name: my-tekapp
  annotations:
    description: The web server's http port.
  labels:
    application: my-tekapp
spec:
  ports:
    - name: 9080-tcp
      port: 9080
      targetPort: 9080
      protocol: TCP
    - name: 9443-tcp
      port: 9443
      targetPort: 9443
      protocol: TCP
    - name: http
      port: 9082
      targetPort: 9082
      protocol: TCP
  selector:
    deploymentConfig: my-tekapp
  type: ClusterIP
  sessionAffinity: None